// This file was auto-generated by SceneListCheck!

public enum Scenes 
{
	CreateAnimation = 0,
	Exams_choice = 1,
	Exam1 = 2,
	Exam2 = 3,
	Exam4 = 4,
	Exam5 = 5,
	Exam6 = 6,
	Exam7 = 7,
	Exam8 = 8,
	Exam9 = 9,
	Exam10 = 10,
	Exam11 = 11,
	Exam12 = 12,
	Exam13 = 13,
	Exam14 = 14,
	Exam15 = 15,
	Exam16 = 16,
	Exam17 = 17,
	Exam18 = 18,
	Exam19 = 19,
	Exam20 = 20,
	Exam21 = 21,
	HydrotoraxExam = 22,
	PneumotoraxExam = 23,
	Autorization_first_scene = 24,
	Examining_menu_scene = 25,
	ExamManager_scene = 26,
	Administrator_menu_scene = 27
}

