// This file was auto-generated by SceneListCheck!

public enum Scenes 
{
	CreateAnimation = 0,
	Autorization_first_scene = 1,
	Exams_choice = 2,
	Exam1 = 3,
	Exam2 = 4,
	Exam4 = 5,
	Exam5 = 6,
	Exam6 = 7,
	Exam7 = 8,
	Exam8 = 9,
	Exam9 = 10,
	Exam10 = 11,
	Exam11 = 12,
	Exam12 = 13,
	Exam13 = 14,
	Exam14 = 15,
	Exam15 = 16,
	Exam16 = 17,
	Exam17 = 18,
	Exam18 = 19,
	Exam19 = 20,
	Exam20 = 21,
	Exam21 = 22,
	HydrotoraxExam = 23,
	PneumotoraxExam = 24,
	TibiaExam = 25,
	EyeDiabeticExam = 26,
	EyeRetinaExam = 27,
	Examining_menu_scene = 28,
	ExamManager_scene = 29,
	Administrator_menu_scene = 30,
	AuscultationLungsExam = 31
}

